#!/usr/bin/env bash

NIX_RUN=""
case "$OSTYPE" in
  "darwin"*)
    NIX_RUN="github:LnL7/nix-darwin"
    ;;
  "linux-gnu"*)
    NIX_RUN="github:nix-community/home-manager"
    ;;
  *)
    echo "unhandled os: ${OSTYPE}" && exit 1
esac


echo "nix run ${NIX_RUN} ${@}"
nix --extra-experimental-features nix-command \
    --extra-experimental-features flakes \
    run ${NIX_RUN} "$@"
