#!/usr/bin/env bash

case "$OSTYPE" in
  "darwin"*)
    if command -v darwin-rebuild &> /dev/null; then
      set -x
      darwin-rebuild "$@"
    else
      set -x
      nix --extra-experimental-features nix-command \
          --extra-experimental-features flakes \
          run github:LnL7/nix-darwin -- "$@"
    fi
    ;;
  "linux-gnu"*)
    set -x
    nix --extra-experimental-features nix-command \
        --extra-experimental-features flakes \
        run github:nix-community/home-manager -- "$@"
    ;;
  *)
    echo "unhandled os: ${OSTYPE}" && exit 1
esac

